site_name: MkDocs Captions Demo

theme:
  name: material

markdown_extensions:
  - pymdownx.extra: {}
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  caption:
    additional_identifier: ["List", "Code"]
    custom:
      enable: true
